### ISSUE TITLE
US 5 - Favorite Page

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#13]
## Value proposition
As a plant enthusiast 
I want to bookmark my favorite plants 
In order to highlight them and have all my favorite plants collected in one place.

## Description
![image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/40d011a7-02b9-4d83-a06a-d82c3915eaab)

## Acceptance criteria
- [ ] a favorite button is displayed at the homepage on each plant card and at the detailspage
- [ ] the user can toggle the favorite button on the homepage as well as on the detailspage and on the favorite page
- [ ] by clicking the favorite button the icon changes its appearance when marked or unmarked and adds or removes recipes from the favorite page
- [ ] a navigation bar with two icons is displayed at the bottom which navigates the user to favorite page (heart icon) and to the homepage (home icon)
- [ ] the favorite page lists all plants that have been marked as favorites

## Tasks
- [ ] create the feature branch "feature-favorite-button"
- [ ] create a new favorite page, that renders all the plants that are marked as a favorite in a list, same as at the overview page
- [ ] create a component NavigationBar and renders the navigation at the bottom of the homepage and favorite page
- [ ] create Links to the corresponding pages (homepage, favorite page)
- [ ] implement two Icons, one for the homepage (home) and one for the favorite page (heart)
- [ ] create a new component "FavoriteButton"
- [ ] add a toggle function
- [ ] render the component "FavoriteButton" at the homepage, detailspage and favorite page
- [ ] create a local storage which contains all favorited plants

**Comment by ThomasKirst** [comment]
Looks great! Go for it 😃🚀
