### ISSUE TITLE
US7 - Delete Plant Preferences

### ISSUE THREAD

**Issue by jantillidie** [MartaJaekel/Plantbuddy#15]
## Value proposition

As a plant Enthusiast,
I want to be able to delete my personal plant preferences
In order to clean up my preferences list or to start over from scratch.

## Description

![image](https://github.com/MartaJaekel/Plantbuddy/assets/82001155/d46b2317-9943-4248-9dff-77a726a44434)

## Acceptance criteria

- [ ] the list item that represents the preference has a clear icon (X/cross)
- [ ] when clicking the clear icon an overlay appears and ask 'Do you really want to delete this preference'
- [ ] the overlay has a 'okay' and a 'cancel' button
- [ ] clicking 'cancel' cancels the delete process
- [ ] clicking 'okay' will delete the preference
- [ ] after clicking 'okay' the preference list item is gone

## Tasks
- [ ] create a feature branch 'feature-delete-preference'
- [ ] add a clear icon to the preference list component
- [ ] add event handling to the clear icon, clicking it should trigger a delete action
- [ ] create confirmation modal that appears after clicking the icon
  - [ ] add the text 'Do you really want to delete this preference' to the modal
  - [ ] add a 'okay' button to the modal
  - [ ] add a 'cancel' button to the modal
- [ ] add functionality to the 'cancel' button that closes the modal and nothing else
- [ ] add event handling to the 'okay' button to proceed with the deletion
- [ ] add a state update to delete the preference after clicking the 'okay' button
- [ ] removing the deleted item from the preferences list that is displayed on the preferences page
