### ISSUE TITLE
US8 - Edit Plant Preferences

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#17]
## Value proposition
As a plant enthusiast, 
I want to be able to edit my own preferences
In order to adjust my preferences I already created.

## Description
![image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/1ff5dbb1-8ebc-421c-9bba-b9d97d11595d)

## Acceptance criteria

- [ ] There is an edit button next to the preference list item
- [ ] The edit button opens the form with the pre filled data from the specific preference
- [ ] The heading is Edit Preference
- [ ] The user can now adjust the data
- [ ] The save button redirects the user to the preference page and saves the new data
- [ ] The cancel button redirects the user to preference page without changing the data
 
## Tasks
- [ ] Create a feature branch feature-edit-preferences
- [ ] Create a edit button that links to the preference form
- [ ] Create a link on the cancel button that redirects back to the preference page
- [ ] Create button SaveChange that updates the preference list item and redirect to the preference page
