### ISSUE TITLE
 US9-Category-specific care guides

### ISSUE THREAD

**Issue by MartaJaekel** [MartaJaekel/Plantbuddy#19]
## Value proposition
As a plant enthusiast
I want to be able to access different plant categories
in order to have detailed informations  on how to take care of plants within a particular category.

## Description
-![Image](https://github.com/MartaJaekel/Plantbuddy/assets/147980927/b4e8af76-1a31-49e2-8264-a9ada3550ae1)

## Acceptance criteria
- [x] a leaf icon is added to the navigation bar in order to navigate to the category page
- [x] there is a title "plant categories" on the category page
- [x] the page includes six categories :
  - [x] succulents
  - [x] palms
  - [x] flowering plants
  - [x] foliage plants
  - [x] herbs
  - [x] trees 
- [x] when clicking on a category we get to the category details page
- [x] the page displays the name of the category , a brief description and different category specific care informations
- [x] on the top left corner there is an icon which brings us back to the overview of the categories 

## Tasks
- [x] create a new branch "feature-plant-categories"
- [x] create a link on the leaf icon that brings the user to the category page
- [x] create a category page that renders  the categories
- [x] create a list that renders the categories 
- [x] add a link to each category to get to the individual category details
- [x] create a component that renders the category details
- [x] add a description text of the category
- [x] create a list with different category-specific care informations, which will be retrieved from an existing array 
- [x] implement a back-arrow icon as a Link to get back to the categories overview page

**Comment by ThomasKirst** [comment]
Looks great! Just one question: where does the data come from – will it be a static array with the information or will the data be retrieved from the database?

**Comment by MartaJaekel** [comment]
We already have a static array of plants and where wondering if its possible to add the categories and the  respective care informations  to this existing array or create a separate one
