### ISSUE TITLE
US - Refactoring Plant Data and Filter Function

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#20]
## Value proposition
As a plant enthusiast,
I want to be able to search from a larger collection of plants based on specific criteria like light requirements, water needs, and plant size,
so that I can easily find plants that fit my living space and care capabilities to increase my success in growing healthy plants.

## Description

![Image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/7f2b04f2-c07e-43c5-bb85-6c0500fc4291)

## Acceptance criteria
- [ ] on the homepage is a larger selection of plants
- [ ]  the filter function has been simplified and made clearer, there are now only three options to choose from, with the exception of the filter for pet-friendliness, which is still yes or no

## Tasks
 - [ ] create the feature branch "feature-refactoring"
 - [ ] add more plants to the data.js
 - [ ] simplify the water needs, sun requirement and size options
 - [ ] add new images to the newly created plants
 - [ ] remove not needed useEffect
 - [ ] adjust the filter values according to the simplified options

**Comment by mbosselmann** [comment]
Hi Team PlantBuddy,
nice user story! 👍 Here are my remarks:

**Value Proposition**
- I think this could be a little bit more specified:

As a plant enthusiast, 
I want to be able to search from a larger collection of plants based on specific criteria like light requirements, water needs, and plant size, 
so that I can easily find plants that fit my living space and care capabilities to increase my success in growing healthy plants.

**Description**
- I think it would be good a new wireframe that shows how the simplified filter functionality would look like. :)

**Acceptance Criteria**
- "all previous features still work" - You do not need to mention this. This is what we always want. 💪 
- For the plant details: Will there be any difference regarding the data that is displayed for the user? As if you want to simplify the water needs, does this also mean that the data will look different on the plant details page? This should be specified too and if so and updated wireframe should be included. :)
- "the filter function is simplified and clearer" - I think it should be more precise described what the new filter function would look like. (For example questions that should be answered: Are there only three options for each filter topion or how many filter options will the user have?)

**Tasks**
- "delete the useEffect in the PlantList because we do not need it as search is already a state the component will be updated on every state update. Therefore, the error state and the plants state are not needed here too." - :D
  - I think you can reduce this to "refactor PlantList component (remove not needed useEffect)". ;)

**Comment by franziska-caroline** [comment]
Many thanks for the comments @mbosselmann ! :)
I have integrated the points into our US once. Regarding the Acceptance Criteria: 
Nothing will change in the presentation of the data for the plants themselves. The data has only been simplified slightly, but everything is displayed in the same way as before.

**Comment by mbosselmann** [comment]
LGTM! 🦊
