### ISSUE TITLE
US - Counter Function

### ISSUE THREAD

**Issue by jantillidie** [MartaJaekel/Plantbuddy#21]
## Value proposition
As a plant enthusiast
I want to see the number of plants displayed after using the search or filter function
in order to know how many plants are being shown out of the total

## Description
Showing the actual number of search or filter results will enhance the user experience by getting immediate feedback on the effectiveness of the search/filter function.

![image](https://github.com/MartaJaekel/Plantbuddy/assets/82001155/c42be42c-c955-4d7e-bc55-12164c1a807c)

## Acceptance criteria
- [ ] When performing a search or filter action, a sentence should be displayed above the list of filtered plants stating 'showing X of 40 plants', where the X reflects the number of the currently displayed plants.
- [ ] If no plants are found, the sentence should read 'showing 0 of 40 plants'.
- [ ] The counter should update in real-time as the user modifies their search/filter criteria.

## Tasks

- [ ] Create the feature branch 'feature-counter'
- [ ] Update the SearchField and FilterForm components to include a counter that tracks the number of the displayed plants
- [ ] Create a function that calculates the number of plants currently being displayed
- [ ] Display the results of the counter above the list of filtered plants.

**Comment by mbosselmann** [comment]
Hi Team PlantBuddy,
great user story so far! I just thought that it might be better to display the text above the list. Here is my reasoning: If the list is longer and the user user needs to scroll down through this longer list the user does not always see this text and this would contradict the benefit of this user story. What do you think? 🤔

**Comment by jantillidie** [comment]
Makes sense, i will change it.

**Comment by mbosselmann** [comment]
LGTM! 🦊
