### ISSUE TITLE
US- Sorting Plants

### ISSUE THREAD

**Issue by MartaJaekel** [MartaJaekel/Plantbuddy#22]
## Value proposition
As a plant enthusiast 
I want to be able to view plants based on their name or size
so that I can easily organise and compare different plants to find ones that best fit my available space and aesthetic desires.
## Description

![image](https://github.com/MartaJaekel/Plantbuddy/assets/147980927/7f3281bf-18f2-4bae-a18b-3c516a26cc15)

## Acceptance criteria
- [x] A dropdown menu  with the title sort is displayed on the HomePage
-  [x] the dropdown includes the following options:
   - [x] sort the name from A to Z(default)
   - [x] sort the name from Z to A
   - [x] sort the size from S to L
   - [x] sort the size from L to S
 - [x] if there is displayed a plant list that  has been already filtered by the Search Bar, by selecting a sort option the user will see the whole plant list again but sorted 

## Tasks
- [x] create the feature branch "feature-sort"
- [x] create a sort plants component 
- [x] create a dropdown selection field with the title "sort"
- [x] create a state variable to keep track of the chosen sorting option
- [x] create a function to handle changes in the sorting option

**Comment by mbosselmann** [comment]
Hi Team PlantBuddy,
nice user story! 👍  I have some remarks for you to optimize this user story a little bit:

**Value Proposition**

I think the benefit of this user story can be more specified. My suggestion:
As a plant enthusiast,
I want to be able to view plants based on their name or size,
so that I can easily organize and compare different plants to find ones that best fit my available space and aesthetic desires.

**Description & Acceptance Criteria**
- I think your wireframes and acceptance criteria do not fully match yet. You wirte as criterion that there is default sort of your plants, but your first wireframe does not reflect this. As it is a good idea to have a default sort, I would suggest to just remove the first wireframe and use the third one to show the default. And then add another example that shows the different plant list if selected.
- I also think the text "Sort" should be placed outside of the drop down menu to always be visible for the user.
- And it would be nice if the drop down menu has enough space for the whole text of each option.
- I think one aspect that should be mentioned is what happens when the plant list is already filtered. Will the selected plant list be sorted or will the user see the whole plant list again but sorted? 🤔 

**Tasks**
- I'm not sure, but maybe you need to think about whether your plant data matches the sort options well or if you need to update the data or write a sort function that can handle it? 🤔 

I hope this does help! :)

**Comment by mbosselmann** [comment]
LGTM! 🦊 

(I would just switch the second and the first wireframe as for me the second wireframe shows the default sort while the first wireframe shows to me how you can select another option. :) )

**Comment by MartaJaekel** [comment]
@mbosselmann yeah that might be better , i will adjust it 🙂
