### ISSUE TITLE
US - Category Specific Color Coding

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#23]
## Value proposition
As a plant enthusiast,
I want to have a better overview of the plants and to easily distinguish which category each plant belongs to.

## Description
![image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/dd3e12bc-ee82-4bfd-8c90-00207d2b955f)

## Acceptance criteria
- [ ] The color coding should be consistent across the application for a cohesive and intuitive user experience
- [ ] Users should be able to quickly discern the category of a plant by its color, contributing to a more efficient and enjoyable browsing experience

## Tasks
- [ ] create a feature branch "feature-colorcoding"
- [ ] Define and apply specific colors for each plant category in the user interface
- [ ] Ensure consistency in color coding across all relevant components

**Comment by mbosselmann** [comment]
Dear Team PlantBuddy,
this is a good start! 👍 Here are my remarks to improve your user story:

First of all: What are the plant categories? Are they categorized by water needs, sun requirements, size or another category (plant species?)? This should be specified in your value proposition and also mentioned in your acceptance criteria. I think the color coding and filter feature could also benefit from this so that you can select the plants by this category (if this is a new one). :) But this would be a whole new user story then. Let us first focus on the color coding itself. 🎨 

**Value Proposition**
As a plant enthusiast, 
I want a color-coded overview of plants, where each color represents a specific category (include here which categories), 
so that I can easily distinguish and understand the different care needs of each plant at a glance.

I hope this does help. :)

**Comment by franziska-caroline** [comment]
@mbosselmann thank you for your feedback! :)
