### ISSUE TITLE
Implement MongoDB Functionality - Read

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#28]
## Value proposition
As a plant enthusiast, 
I want my data to be securely stored and accessible across devices,
so that I can have a persistent and consistent, personalized experience.

## Description
![image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/77f6ee88-48ca-496a-948c-e7a2a0d9d172)

## Acceptance criteria
- [x] the plants, including the name and other details, are stored in the MongoDB database and are therefore consistent across devices

## Tasks
- [x] set up a database and use the data from `lib/data.js` (without the id) to create a collection
- [x] develop functionality to Read plants:
  - [x] install mongoose with npm install mongoose and SWR
  - [x] create a .env.local file (user and pw for all)
  - [x] create a `db/connect.js` file 
  - [x] create a `db/models/Plant.js` and create a schema 
  - [x] create `pages/api/plants/index.js` and `pages/api/plant/[id]/index.js`
  - [x] in `pages/api/index.js` write function for GET request for all plants
  - [x] in `pages/api/[id]/index.js`write function for GET request for the details page
  - [x] import SWR in PlantList.js and start fetching data from MongoDB using the SWR-hook
  - [x] make sure to name the data-object (data: plants) so that the functionalities work as before
- [x] Implement error handling in for MongoDB connection issues

**Comment by ThomasKirst** [comment]
Looks quite good overall!

Just two suggestions:

- you could place your api routes in a folder `plants`, so the path would be `pages/api/plants/index.js` and `pages/api/plants/[id]/index.js`. This would be helpful if you plan to use other models (like the Journal) as well, so you would have some separation here. But in a first iteration it´s also ok to do it in the way you outlined it.
- I would name the schema, model and file in the singular (`Plant` instead of `Plants` – `db/models/Plant.js`) – the DB collection will be called `plants` automatically thereafter.

These are just suggestions and implementation details that go into more detail than usually necessary 😃

**Comment by franziska-caroline** [comment]
Thank you @ThomasKirst ! We have adopted your comments so that we can be more open about how we work with the Db in the future and whether further models will be added. :)
