### ISSUE TITLE
US- Edit Plant Journal

### ISSUE THREAD

**Issue by MartaJaekel** [MartaJaekel/Plantbuddy#29]
## Value proposition
As a plant enthusiast 
I want to be able to edit my plant journal 
In order to adjust or update my journal entries 
## Description
![img](https://github.com/MartaJaekel/Plantbuddy/assets/147980927/4c1a5508-237b-4954-884a-e1d328c65ca6)

## Acceptance criteria
- [ ] clicking the entry on the overview page the user will get to the entries details page 
- [ ] on the entries details page there is an edit button up in the right corner
- [ ] clicking the edit button the user can adjust the pre filled entry details
- [ ] once in edit mode there is displayed a save button and a cancel button underneath the form 
- [ ] the save button saves the new data and shows the updated entry details to the user
- [ ] the cancel button cancels the editing process and brings the user back to the previous entries details page 
without saving any changes.

## Tasks
- [ ] create a new branch "feature-edit-journal"
- [ ] create an edit button that switches the view to an edit mode
- [ ] allow the user to make adjustments
- [ ] create a save button that captures the updated data
- [ ] create a cancel button that cancels the editing process
- [ ] implement a useState to manages the state of the entries
- [ ] implement a function that handles the change of the data

**Comment by ThomasKirst** [comment]
The third screen, where the edit process takes place, doesn´t really show the full form.
Where can the user edit the plant´s name or the picture?
Maybe you want to show the same form as it is used for the creation of the plant journal entry – this time only to be filled with the pre-existing data?
Then you would also place the save or update button in the same position as on the create form.

**Comment by MartaJaekel** [comment]
@ThomasKirst  yeah you are right , it makes sense that in the edit the same form gets showed , we will adjust it 🙂

**Comment by mbosselmann** [comment]
LGTM! 🦊
