### ISSUE TITLE
US- Plant Journal delete entries

### ISSUE THREAD

**Issue by MartaJaekel** [MartaJaekel/Plantbuddy#33]
## Value proposition
As a  plant enthusiast 
I want to be able to delete entries
In order to  organise my list of entries on the overview page 
## Description
![img](
https://github.com/MartaJaekel/Plantbuddy/assets/147980927/7fe6f024-1e57-4979-b7e6-2606166a57e7
)
## Acceptance criteria
- [ ]  the list item that represents the entry has a clear icon (X/cross)
- [ ]  when clicking the clear icon an overlay appears and ask's 'Do you really want to delete this activity?'
- [ ] the overlay has a 'okay' and a 'cancel' button
- [ ] clicking 'cancel' cancels the delete process
- [ ] clicking 'okay' will delete the entry
- [ ]  after clicking 'okay' the entry list item is gone
## Tasks
- [ ] create a feature branch 'feature-delete-entry'
- [ ] add a clear icon to the entry list component
- [ ] add event handling to the clear icon, clicking it should trigger a delete action
- [ ]  create confirmation modal that appears after clicking the icon
   - [ ] add the text 'Do you really want to delete this activity' to the modal
   - [ ] add a 'okay' button to the modal
   - [ ] add a 'cancel' button to the modal
- [ ] add functionality to the 'cancel' button that closes the modal and nothing else
- [ ] add event handling to the 'okay' button to proceed with the deletion
- [ ] add a state update to delete the entry after clicking the 'okay' button

**Comment by ThomasKirst** [comment]
All good! Just one minor thing: you could switch the positions of **Cancel** and **Okay**, since users generally expect the positive confirm action on the right and the cancellation action on the left.
See for example here:
https://m3.material.io/components/dialogs/specs
