### ISSUE TITLE
US - Connect Detail Pages 

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#36]
## Value proposition
As a plant enthusiast 
I wish to navigate seamlessly from a plant's detail page to its related plant category page,
So that I can get all necessary information with greater ease.

## Description
![image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/293cf763-c7ef-4ec1-a721-1a4b0a307e08)

## Acceptance criteria
- [ ] On the plant detail page is a new leaf icon (same as in the navigation bar to go to the category page) with the title category and the corresponding category name
- [ ] The Word "Category" is underlined to highlight it and to suggest that it is a link
- [ ] by clicking on the icon and or text the user gets to the corresponding category page to learn more about the category 
- [ ] by clicking on the back arrow in the left hand corner, the user navigates back to the plant detail page

## Tasks
- [ ] create a new branch "feature-connect-pages"
- [ ] add a new item to the existing list (category + category name)
- [ ] implement a new icon (use the same icon as in the navigation bar for the category page)
- [ ] create a Link to get to the corresponding category detail page

**Comment by mbosselmann** [comment]
Hi Team PlantBuddy,
a really nice enhancement for your users! 👍 Nevertheless, I have some remarks:

**Value Proposition:**
I think we can shorten this a little bit. My suggestion:

As a plant enthusiast,
I wish to navigate seamlessly from a plant's detail page to its related plant category page,
So that I can get all necessary information with greater ease.

**Description/ Acceptance Criteria:**
- Your last criterion and the description do not match. 🤔 I think the description needs to be updated or does the text does not belong to the link? Then maybe change the description to make this clear as currently the text could also mean that the links leads back to the plant categories page. :)
- I think there should also be a handling about what happens when there is no category for the plant.
- And I would to let the category link somehow visually differ from the rest of the displayed plant information so that the user can better notice that this is clickable. :)

I hope this does help. :)

**Comment by franziska-caroline** [comment]
Thank you @mbosselmann! 😊 I've updated the US based on your comments, the only thing we don't need is error handling because all our plants have a category / there is always a category for the plants and right now we don't plan to have more plants
