### ISSUE TITLE
Plant List

### ISSUE THREAD

**Issue by MartaJaekel** [MartaJaekel/Plantbuddy#4]
# US1 - Plant List

## Value Proposition

As a plants enthusiast </br>
i want to see a list of plants </br>
so that i can have an overview of different plants to get some inspiration

## Description

a list of all the plants </br>

![Image](https://github.com/MartaJaekel/capstone-project/assets/147980927/b38edbbf-e9ce-418e-ba2f-f0c504b5aeef)

## Acceptance Criteria

- [x] there is an app title above the list of current plants
- [x] there is a list of random plants displayed on the homepage
- [x] each plant of the list includes following details:
  - [x] name of the plant
  - [x] image of the plant
- [x] the list of plants is vertically scrollable
- [x] app title is always visible
- [ ] an error message is displayed to the user if there is an issue loading the plants data

## Tasks

- [x] create the feature branch "plant-list"
- [x] create your own database with example plants
- [x] create card component for the HTML structure(grid view)which renders in Homepage:
- [x] name of the plant
- [x] image of the plant
