### ISSUE TITLE
Task - Refactoring Stylings

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#44]
## Tasks
- [ ] outsource all repetitive elements (e.g. the back button) into own components
- [ ] consistent styling
    - [ ] check that all buttons and cards have the same border radius
    - [ ] font sizes, weights, etc
 - [x] placement of the favorite button button on the detailspage
 - [x] the back button could look better (the arrow is not centered)
 - [ ] Design for different browsers 
 - [x] on the Journal Details page only show the headings and text fields if they have been filled in the form ( XY > 0 ? : )
