### ISSUE TITLE
US - Responsive Design

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#46]
## Value proposition
As a plant enthusiast
I want to have a great visual experience on different devices
So that I have a more pleasant and beautiful visual use of the app

## Description
![image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/8b88aae4-0015-4554-925c-8ec672659c81)

## Acceptance criteria
- [x] the app looks appealing both on mobile and desktop
- [x] the images on the details pages are adapted to the new format and are not too large
- [x] the plant cards have a space to the sides in the desktop view 

## Tasks
- [x] create a new branch feature-responsive
- [x] work with media queries in the styling
    - [x] add padding to the plant cards on the homepage
    - [x] adjust the detail pages

**Comment by CJAkkuec** [comment]
>  the app looks appealing both on mobile and desktop

I'd suggest that "appealing" is probably fairly subjective. Perhaps something like "the app design renders as intended for a mobile client as well as a desktop client"?

>  the images on the details pages are adapted to the new format and are not too large

"not too large" again feels more like an opinion rather than a guideline. Perhaps limit the file size to a certain maximum width?
