### ISSUE TITLE
US - Authentification (Frontend)

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#47]
## Value proposition
As a plant enthusiast
I want to be able to login to the app
In order to have access to all restricted functionalities and pages. 

## Description
![Image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/b0cc2c9f-8b5f-4559-866e-6c6e69de8b99)

## Acceptance criteria
- [ ] when the user clicks on one of the restricted pages, favorite page, journal page or preference page, there is a request message to log in
- [ ] under the message is a sign in button
- [ ] by clicking on the button the user gets to a page where he can find github as third party provider to log in 
- [ ] when you are logged in, there is a colored bar at the top with your name and the option to log out on every page with the plantbuddy logo
- [ ] when you are logged in, you can use the restricted functionalities and pages as favor your plants 
- [ ] when the user is not logged in the favoring hearts on the plant cards and the plant detail page are not visible, only when you are logged in, you have the option to favorite 
- [ ] by clicking on the log out button the user logs off and the restricted pages are restricted again

## Tasks
- [ ] create a new branch feature-authentification
- [ ] Register O-Auth-App at github
- [ ] Basic Setup 
  - [ ] npm installl next-auth 
  - [ ] API route define
  - [ ] provider session context pages/api
- [ ] Save frontend
   - [ ] use the useSession hook
   - [ ] conditional render the favorite page, journal page, preference page and the favorite hearts
   - [ ] build login
- [ ] create a component for the logout bar

**Comment by doemser** [comment]
The value proposition is concise but could be more descriptive. Consider adding why the restricted functionalities are valuable to a plant enthusiast. 

When a user logs in or out, consider adding a confirmation message or visual feedback to improve user experience.

But I will still approve
