### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by MartaJaekel** [MartaJaekel/Plantbuddy#5]
# US2 - Card Component

## Value Proposition

As a plants enthusiast </br>
i want to see a detail page of the plant </br>
so that i can get all essential information about how to take care of the plant.

## Description

a detail page of a plant </br>
![Image](https://github.com/MartaJaekel/capstone-project/assets/147980927/84b97f21-e9e9-4648-a5ae-ed1b969d57d1)

## Acceptance Criteria

- [x] clicking a plant card from the list to show the details page
- [x] an image of a plant is displayed
- [x] the plant name is displayed
- [x] a list of size, water need, sunlight and temperature is displayed
- [x] a description is shown
- [x] an Icon is implemented at top left hand corner and when clicked gets the user to the
      home page

## Tasks

- [x] implement dynamic routing
- [x] create the feature branch "detail-page"
- [x] create a new page named detail page
- [x] create a Link to get to the individual detail page
- [x] implement image
- [x] add a list of size, water, sunlight and temperature
- [x] add a description text of the plant
- [x] implement a icon/svg of a back-arrow-icon as a Link to get back to the homepage "/"

**Comment by BirkBee** [comment]
Looks very nice! 🙌 
 Keep up the good work! 🚀
