### ISSUE TITLE
US - Implement MongoDB Functionality (CRUD)

### ISSUE THREAD

**Issue by jantillidie** [MartaJaekel/Plantbuddy#54]
## Value proposition

As a plant enthusiast
I want to manage all my personalyzed entries and settings,
So that I can access them seamlessly across different devices and browser sessions.

## Description

- This is about migrating user-specific data from local storage to a remote database with MongoDB to enhance data persistence and accessibility across different devices.

## Acceptance criteria

- [ ] User-related data is stored in a remote Database
- [ ] Users can log in from every device or browser and can access their data

## Tasks

- [ ] Create a feature branch 'feature-mongodb-crud'
- [ ] Create collections for preferences, journal and favorites
- [ ] Create db models for preferences, journal and favorites
- [ ] Update the application logic to use MongoDB for storing and retrieving preferences, journal and favorites

**Comment by mbosselmann** [comment]
Hi Team PlantBuddy,
good job! 👍 Two remarks for you:
- I would remove the first acceptance criterion as this is more a developer task and you describe in more detail what you want to do. But another criterion that can be added here is to describe that the user specific data is not shown when the user is not logged in.
- As a note: For the database implementation, you can decide between two approaches: the first one is the one you described with one collection for each type of data (preferences, journal entries and favorites). It might be easier though to have one users collection and inside if each user object are stored the preferences, journal entries and favorites. But it is up to you to decide what to do and maybe it is easier for you to work with multiple collections. :)

I approve this user story!
