### ISSUE TITLE
US - Image Upload

### ISSUE THREAD

**Issue by franziska-caroline** [MartaJaekel/Plantbuddy#56]
## Value proposition
As a plant enthusiast 
I want to be able to upload images to my personal journal
In order to use my own images from my gallery.

## Description
![Image](https://github.com/MartaJaekel/Plantbuddy/assets/143591286/f4a19205-e8a5-4da5-a210-cb5e8459c753)

## Acceptance criteria
- [ ] An Upload Button for the image is added in the form where the user can create a new entry
- [ ] The user is informed that only certain image formats are allowed (png, jpg, jpeg and webp)
- [ ] Clicking the upload button opens up a "picker" where the user can select an image from his device
- [ ] Afterwards the name of the selected image is displayed in the form
- [ ] After creating a new entry the image is than visible 

## Tasks
- [ ] create a new branch feature-image-upload
- [ ] sign up to cloudinary
- [ ] Retrieve API Key and API Secret
- [ ] install cloudinary npm install cloudinary
- [ ] add the attributes accept=".png, .jpeg, .jpg, .webp" to the image input element
- [ ] create a remove "X" button to remove the selected image
- [ ] cloudinary is used to store the image(s)

**Comment by franziska-caroline** [comment]
@Julia-Pickel thanks for your feedback 😊
We already have an image upload feature, but only if you use an image from Google, Unsplash or Wikipedia.
Since the image is required, we don't have a placeholder image and the user is informed to upload an image.
