### ISSUE TITLE
US- About Us page

### ISSUE THREAD

**Issue by MartaJaekel** [MartaJaekel/Plantbuddy#57]
## Value proposition
As a plant enthusiast, I would like to access information about the developers of the app 
in order to  understand better the background and motivations behind the app's creation
## Description
![img](https://github.com/MartaJaekel/Plantbuddy/assets/147980927/a517ef6e-b18f-4f33-9efa-5f515b1413fb)

## Acceptance criteria
- [ ] There is an  icon on the top left of the homepage
- [ ] When clicking on the icon the user gets to the "About us" page
- [ ] On the "About us" page are displayed three cards each one with a picture of the developer, the name and a Github Link
- [ ] When clicking on the Github Link the User gets to the Github Profile Page 
- [ ] There is a Back Button to get back to the homepage

## Tasks
- [ ] create a branch feature-about
- [ ] add a representative  about icon to the homepage 
- [ ] create a new page about.js
- [ ] create a link that brings the user to the "About us" page
- [ ] create three cards , one for each developer of the app

**Comment by F-Kirchhoff** [comment]
LGTM 🚀
