### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by MartaJaekel** [MartaJaekel/Plantbuddy#6]
# US3 - Search Function

## Value Proposition

As a plants enthusiast </br>
i want to be able to search through the plant list </br>
so that i can find a specific plant.

## Description

a search bar at the top of the list </br>

![Image](https://github.com/MartaJaekel/capstone-project/assets/147980927/56c81905-e8c9-4481-a936-f814dcb8545f)

## Acceptance Criteria

- [x] clickable search bar should be prominently displayed on the homepage
- [x] the search bar should feature an input field
- [x] the search bar should include a search button or icon that users can click on to initiate the search
- [x] the search bar should include a delete button or icon that users can click on to reset the search
- [x] the search results are updated with each new input
- [x] Plants that match the search are displayed
- [x] if there are no results, a error message is displayed that we can't find anything with the name XY
- [x] if we don't enter anything in the search field or delete the search with the "x"-button, all plants are displayed

## Tasks

- [x] create the feature branch "Searchfunction"
- [x] create a form field component with an input field
- [x] update the design and implement the search bar component
- [x] search field works `onChange`, allowing users to initiate a search
- [x] integrate a search button or an icon (eg. SVG) to the search bar
- [x] integrate a delete button or an icon (eg. SVG) to the search bar
- [x] define the criteria for generating relevant search results (plant common name)
- [x] implement an error message in case no results are found
